### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/osmextract#91]
So far ~1% is covered.

That's good in the early development stage but now the function names (and package name, finally!) is stable we can start thinking about this. 

```r
covr::report()
```

Gives 

![image](https://user-images.githubusercontent.com/1825120/88174185-c3d63480-cc1b-11ea-850c-13448da5ffd9.png)

**Comment by agila5** [comment]
- [ ] match 
- [ ] download
- [ ] vectortranslate
- [ ] read
- [ ] get
- [ ] update
- [x] providers

**Comment by agila5** [comment]
One questions here since I've never written any test. There are several code lines that are missed by the tests simply because they are just checking that the input data is specified in a particular format and I'm not sure if it does make sense to write several tests like `expect_error(function(wrong_input))`. What's the best practice in this case?

**Comment by Robinlovelace** [comment]
> There are several code lines that are missed by the tests simply because they are just checking that the input data is specified in a particular format and I'm not sure if it does make sense to write several tests like expect_error(function(wrong_input)). What's the best practice in this case?

Not sure. I think people can over-emphasise the importance of tests and we shouldn't be aiming for "100% coverage" just because it sounds good, so my first answer is:

> Don't spend time writing tests unless they're useful
